openapi: 3.1.0
x-stoplight:
  id: emz6g9komh9o6
info:
  title: Droff Bridge API
  version: '1.0'
  summary: Droff APIs for third parties
  description: ''
  contact:
    email: info@drofflogistics@gmail.com
servers:
  - description: staging
    url: 'https://api-test.drofflogistics.com'
  - description: production
    url: 'https://api-test.drofflogistics.com'
paths:
  /deliveries:
    parameters: []
    patch:
      summary: Update delivery status
      operationId: editDelivery
      responses: {}
      description: Update delivery status
      requestBody:
        content: {}
        description: Patch user properties to update.
      tags:
        - Delivery
    post:
      summary: Book delivery
      operationId: bookDelivery
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                type: object
                x-examples:
                  Example 1:
                    message: Delivery booked
                    id: 132
                properties:
                  message:
                    type: string
                  id:
                    type: string
              examples:
                Example 1:
                  value:
                    message: Delivery booked
                    id: FGGHJHJKKJ
      description: Book new delivery
      tags:
        - Delivery
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/DeliveryRequest'
components:
  schemas:
    DeliveryRequest:
      type: object
      x-stoplight:
        id: 092b2adc4bcd0
      x-examples:
        Example 1:
          item: string
          pickupLocation: string
          dropoffLocation: string
          dropoffPhoneNumber: string
          clientCash: 0
          additionalInfo: string
          payer: CUSTOMER
      examples:
        - item: Necklace
          pickupLocation: 'Osu, Ringway'
          dropoffLocation: Adenta housing down
          dropoffPhoneNumber: '+23350000000000'
          clientCash: 3000
          additionalInfo: Gold
          payer: BUSINESS
      title: DeliveryRequest
      description: Request body for book a new delivery
      properties:
        item:
          type: string
        pickupLocation:
          type: string
        dropoffLocation:
          type: string
        dropoffPhoneNumber:
          type: string
        clientCash:
          type: integer
        additionalInfo:
          type: string
        payer:
          $ref: '#/components/schemas/PayerEnum'
      required:
        - item
        - pickupLocation
        - dropoffLocation
        - dropoffPhoneNumber
        - clientCash
        - payer
    PayerEnum:
      title: PayerEnum
      x-stoplight:
        id: 1iyua2julzi78
      type: string
      enum:
        - CUSTOMER
        - BUSINESS
      description: Delivery payer options
    DeliveryStatusEnum:
      title: DeliveryStatusEnum
      x-stoplight:
        id: sxg2qf0jejvza
      type: string
      description: Delivery status options
      enum:
        - PENDING
        - ACCEPTED
        - REJECTED
        - IN_TRANSIT
        - COMPLETED
        - RESCHEDULED
  securitySchemes:
    x-api-key:
      name: API Key
      type: apiKey
      in: query
tags:
  - name: Delivery
